version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: passwordmanager
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - ./passwordmanager.sql:/docker-entrypoint-initdb.d/passwordmanager.sql 

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile 
    env_file:
      - ./Backend/.env 
    ports:
      - '80:80'
    depends_on:
      - mysql
